import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/sync-docs.mjs and the pagefind postbuild:
    "content/**",
    "public/synced/**",
    "public/.synced-tmp/**",
    "public/pagefind/**",
    // Local tool folders, both git-ignored: worktrees hold their own build
    // output, and .sdlc-skills holds design and evidence files.
    ".worktrees/**",
    ".sdlc-skills/**",
  ]),
]);

export default eslintConfig;
